version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  qr:
    build:
      context: .
      dockerfile: Dockerfile.qr
    ports:
      - "8000:8000"
    volumes:
      - ./bot.qr.png:/var/www/html/bot.qr.png